### ISSUE TITLE
cant get share maps view in public

### ISSUE THREAD

**Issue by synersignart** [nlybe/Elgg-Sharemaps#11]
Hi sir
just try your plugin I've notice you haven't upload it to the elgg site the new update , any how the 2.1.x of sharemaps does take time to load if run in firefox but faster on chrome 
the logged in users works  but the public doesn't. on the( who can view part)

thanks
hope to see the bug fix

**Comment by nlybe** [comment]
Hello
I have tested in several sites and upload looks to work normally in chrome or firefox.
The same for views, look to work fine for logged-in and public users.
You should check file permissions or any JS conflict with other plugins.

I haven't uploaded yet to Elgg community because there are some small issues when creating maps. But you could disable this option in settings so it will work fine for Elgg 2.1 or greater

Nikos

**Comment by synersignart** [comment]
I see, so does it have to be arrange on a particular format.? since the markers or polygons wont show up in public but the map works

**Comment by nlybe** [comment]
For uploading files, kml or gpx are allowed. It has been tested with several files and different complexity and it works fine.
